spring:
  application:
    name: eurekaServer

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false   # 不向注册中心注册自己
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8761

# region Eureka Server 集群配置
---

spring:
  profiles: server1
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1112/eureka
server:
  port: 1111

---

spring:
  profiles: server2
eureka:
  instance:
    prefer-ip-address: true
    hostname: server2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
server:
  port: 1112

# endregion