spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_account?useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true

custom:
  param1: 'param1'

---

# 本地环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_account?useSSL=false
    username: root
    password: 123456

custom:
  param1: 'param23sdf'

---
# 开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://k8smysql.hanboard.com.cn:8087/db_account?useSSL=false
    username: root
    password: root

---
# 测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://k8smysql.hanboard.com.cn:8087/db_account?useSSL=false
    username: root
    password: root

---
# 产品环境
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://k8smysql.hanboard.com.cn:8087/db_account?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: false


