spring:
  application:
    name: sc-hystrix
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000   # 配置 HystrixCommand 执行的超时时间，单位毫秒